[package]
name = "codepanion-model-client"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
codepanion-config = { path = "../config" }
codepanion-shared = { path = "../shared" }
reqwest = { version = "0.12", features = ["blocking"] }
serde_json = "1.0"

[lib]
path = "src/lib.rs"
